# Generated by Django 4.2.4 on 2024-06-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='QuestionBanks',
            new_name='Banks',
        ),
        migrations.RenameModel(
            old_name='QuestionImages',
            new_name='Images',
        ),
        migrations.RenameModel(
            old_name='QuestionOptions',
            new_name='Options',
        ),
    ]
