# Generated by Django 4.2.4 on 2024-06-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_answer_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Banks',
            new_name='Bank',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
