# Generated by Django 4.2.4 on 2024-06-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_answers_answer_rename_banks_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='bank_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.bank'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SI', 'single_choice'), ('MU', 'multiple_choice'), ('SH', 'short_answer')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question'),
        ),
    ]
