# Generated by Django 4.2.4 on 2024-06-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_answer_answer_text_answer_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.bank'),
        ),
    ]
