# Generated by Django 4.2.4 on 2024-06-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_image_question_id_alter_option_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question'),
        ),
    ]
